#!/usr/bin/env ruby

# I haven't found a clean way to get Sorbet to check this file since the name
# doesn't end in `.rb`.  (If I add `--file bin/braid` to `sorbet/config`, then
# the Sorbet language server doesn't support using Watchman.)  So move all the
# interesting code to `lib/braid/main.rb` and leave this as a launcher that
# doesn't have any code worth type checking. ~ Matt 2022-04-02

require_relative '../lib/braid/check_gem'

require 'braid/main'
